# Removes human DNA by aligning raw reads to the hg38 reference genome using Bowtie2.
# Usage: sbatch --array=1-N%M host_removal_script.job <batch_name>
# Retains only unaligned reads (-f 4) and saves them as compressed FASTQ files via pigz.
# Generates alignment statistics for each sample to track the proportion of host contamination. 

#!/bin/bash
#SBATCH -A uppmax2025-2-380
#SBATCH -M pelle
#SBATCH -p pelle
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=12
#SBATCH -t 5:00:00
#SBATCH -J remove_host_dna
#SBATCH -o /proj/uppmax2025-2-380/project_work/logs/01_host_removal_logs/%j.out
#SBATCH -e /proj/uppmax2025-2-380/project_work/logs/01_host_removal_logs/%j.err


# Check for batch argument
if [ -z "$1" ]; then
    echo "Usage: sbatch --array=1-N%M $0 <batch_name>"
    exit 1
fi
batch=$1

module load Bowtie2
module load SAMtools
module load pigz/2.8-GCCcore-13.3.0

base=/proj/uppmax2025-2-380/project_work
samples=${base}/data/00_raw_data/${batch}/${batch}_fq_files.txt
human_ref=${base}/resources/references/human_reference_genome/hg38.fa.gz

# Extract only the sample name for each sample (not the .fastq.gz extension)
sample=$(sed -n "${SLURM_ARRAY_TASK_ID}p" ${samples})
sample_base=${sample%.fastq.gz}

echo "Performing host removal for sample: ${sample} at $(date) on node $(hostname)."

input=${base}/data/00_raw_data/${batch}/${sample}
out_fastq=${base}/data/01_host_removal/${batch}/${sample_base}_unaligned_to_hg38.fastq.gz
stats_file=${base}/data/01_host_removal/${batch}/${sample_base}_host_alignment_stats.txt

#  Bowtie2 → samtools filter unaligned (-f 4) → FASTQ → pigz. Returns only fastq.gz-files.
#  Saves alignment stats in the file _host_alignment_stats.txt (% mapped etc)
bowtie2 --large-index -x ${human_ref} \
    --end-to-end --very-sensitive --threads 12 \
    -U ${input} \
| tee >(samtools view -b -f 4 -@ 2 - \
	| samtools fastq -@ 2 - \
	| pigz -p 2 > ${out_fastq}) \
| samtools flagstat - > ${stats_file}

echo "Finished with host removal for sample: ${sample} at $(date)."