#!/bin/bash
#SBATCH -A uppmax2025-2-380
#SBATCH -M pelle
#SBATCH -p pelle
#SBATCH -n 4
#SBATCH -t 02:00:00
#SBATCH -J softlink_fastq_files

base=/proj/uppmax2025-2-380/private/DATA/FASTQ/Gok2c
samples=/proj/uppmax2025-2-380/project_work/scripts/01_host_removal_scripts/test_data_fq_files.txt
outdir=/proj/uppmax2025-2-380/project_work/test_data/00_raw_data

while read -r i; do
    echo "Linking: ${base}${i} -> ${outdir}"
    ln -s "${base}${i}" "${outdir}"
done < "$samples"
