#!/bin/bash
#SBATCH -A uppmax2025-2-380
#SBATCH -M pelle
#SBATCH -p pelle
#SBATCH -n 1
#SBATCH -t 01:00:00
#SBATCH -J cleanup_coverage
#SBATCH -o /proj/uppmax2025-2-380/project_work/logs/bowtie2_logs/cleanup_coverage/%j.out
#SBATCH -e /proj/uppmax2025-2-380/project_work/logs/bowtie2_logs/cleanup_coverage/%j.err

BASE=/proj/uppmax2025-2-380/project_work
COVDIR=$BASE/test_data/04_authentication/coverage

echo "Cleanup started at: $(date)"

for SUMMARY in $COVDIR/*/*.coverage_summary.tsv; do
    SAMPLE_DIR=$(dirname "$SUMMARY")
    echo "Processing: $SUMMARY"

    # Read summary line-by-line (skip header)
    tail -n +2 "$SUMMARY" | while IFS=$'\t' read SAMPLE TAXID NAME MAPPED LENGTH BASES PCT DEPTH MAPQ
    do
        # Check for non-informative rows
        if [[ $BASES == "0" && $PCT == "0" && $DEPTH == "0" && $MAPQ == "0" ]]; then
            echo "  → Removing useless files for taxID $TAXID"

            rm -f "$SAMPLE_DIR/${SAMPLE}.${TAXID}.coverage.tsv"
            rm -f "$SAMPLE_DIR/${SAMPLE}.${TAXID}.depth.txt"
        fi
    done
done

echo "Cleanup finished at: $(date)"
