#!/bin/bash
#SBATCH -A uppmax2025-2-380
#SBATCH -M pelle
#SBATCH -p pelle
#SBATCH -n 4
#SBATCH -t 04:00:00
#SBATCH -J compute_coverage
#SBATCH -o /proj/uppmax2025-2-380/project_work/logs/03_bowtie2_logs/compute_coverage/%j.out
#SBATCH -e /proj/uppmax2025-2-380/project_work/logs/03_bowtie2_logs/compute_coverage/%j.err

module load SAMtools/1.22-GCC-13.3.0

# Pathways
BASE=/proj/uppmax2025-2-380/project_work
ALIGNDIR=$BASE/test_data/03_bowtie2
OUTDIR=$BASE/test_data/04_authentication/coverage
mkdir -p "$OUTDIR"

echo "Coverage computation started at: $(date)"

cd "$ALIGNDIR"

# Loop over sample-folders
for SAMPLE in */; do
    SAMPLE=${SAMPLE%/}   

    echo " Sample: $SAMPLE"

    # Output folder for samples
    SAMPLE_OUT=$OUTDIR/$SAMPLE
    mkdir -p "$SAMPLE_OUT"

    SUMMARY="$SAMPLE_OUT/${SAMPLE}.coverage_summary.tsv"
    echo -e "sample\ttaxID\tlength\tbases_covered\tcoverage_pct\tmean_depth\tmean_mapq" > "$SUMMARY"

    # Loop over BAM-files in the sample folder
    for BAM in "$SAMPLE"/*.bam; do
        [[ -s "$BAM" ]] || continue

        # Extract taxID from filename
        # Format: BASENAME.TAXID.bam
        TAXID=$(basename "$BAM" | sed 's/.*\.\([0-9]*\)\.bam/\1/')

        echo "taxID $TAXID"

        # 1. samtools coverage -m
        COV_OUT="$SAMPLE_OUT/${SAMPLE}.${TAXID}.coverage.tsv"

        samtools coverage -m "$BAM" > "$COV_OUT"

        ROW=$(tail -n 1 "$COV_OUT")
        LENGTH=$(echo "$ROW" | awk '{print $2}')
        BASES=$(echo "$ROW" | awk '{print $3}')
        PCT=$(echo "$ROW" | awk '{print $4}')
        DEPTH=$(echo "$ROW" | awk '{print $5}')
        MAPQ=$(echo "$ROW" | awk '{print $7}')

        echo -e "${SAMPLE}\t${TAXID}\t${LENGTH}\t${BASES}\t${PCT}\t${DEPTH}\t${MAPQ}" >> "$SUMMARY"

        # 2. samtools depth -a
        DEPTH_OUT="$SAMPLE_OUT/${SAMPLE}.${TAXID}.depth.txt"
        samtools depth -a "$BAM" > "$DEPTH_OUT"

        echo "Coverage + Depth OK"

    done

done

echo "Coverage computation completed at: $(date)"
