# Batch processes KrakenUniq reports by calling a Python filtering script for each sample.
# Usage: sbatch krakenuniq_filtering_script.job <batch_name> <unfiltered_directory>
# Applies thresholds (1000 kmers, 200 reads) and extracts pathogens using a reference list.
# Automatically organizes the resulting .filtered and .pathogens files into a new output directory.

#!/bin/bash
#SBATCH -A uppmax2025-2-380
#SBATCH -M pelle
#SBATCH -p pelle
#SBATCH -n 1
#SBATCH -t 00:30:00
#SBATCH -J krakenuniq_filtering
#SBATCH -o /proj/uppmax2025-2-380/project_work/logs/02_krakenuniq_logs/%j.out
#SBATCH -e /proj/uppmax2025-2-380/project_work/logs/02_krakenuniq_logs/%j.err

# Check command-line arguments
if [ $# -ne 2 ]; then
    echo "Usage: sbatch $0 <batch_name> <unfiltered_directory>"
    exit 1
fi

batch=$1
input_dir=$2

module load Python/3.13.1-GCCcore-14.2.0
module load SciPy-bundle/2024.05-gfbf-2024a

base=/proj/uppmax2025-2-380/project_work
outdir=${base}/data/02_krakenuniq/${batch}/filtered_krakenuniq_output
mkdir -p $outdir

script=${base}/scripts/02_krakenuniq_scripts/filter_krakenuniq.py
pathogen_list=${base}/resources/krakenuniq_resources/bacterial_pathogens_with_taxid.tab

for i in "$input_dir"/*.krakenuniq.output; do
    sample=$(basename "$i")
    echo "Filtering sample ${sample}..."
    python3 "$script" \
        "$i" \
        1000 \
        200 \
        "$pathogen_list"
done

echo "Done with filtering all samples."

mv ${input_dir}/*.output.filtered "$outdir"
mv ${input_dir}/*.output.pathogens "$outdir"