#!/bin/bash
#SBATCH -A uppmax2025-2-380
#SBATCH -M pelle
#SBATCH -p pelle
#SBATCH -n 16
#SBATCH -t 10:00:00
#SBATCH -J krakenuniq_taxonomic_profiling_test_data
#SBATCH -o /proj/uppmax2025-2-380/project_work/logs/02_krakenuniq_logs/%j.out
#SBATCH -e /proj/uppmax2025-2-380/project_work/logs/02_krakenuniq_logs/%j.err

base=/proj/uppmax2025-2-380/project_work

echo "Loading KrakenUniq in conda environment..."
module load Miniconda3/24.7.1-0
source activate ${base}/environments/conda_envs/krakenuniq
echo "KrakenUniq loaded."

db=/proj/uppmax2025-2-380/private/DATA/DBDIR_KrakenUniq_MicrobialNT_Plus_CompleteGenomes

# .txt file with the file names of the FASTQ-files we want to run. Edit this file depending on the input.
samples=${base}/resources/krakenuniq_resources/samples_to_run_krakenuniq.txt

# COPY DATABASE TO LOCAL SSD ($SNIC_TMP)
echo "Copying KrakenUniq database to \$SNIC_TMP..."
echo "Source: $db"
echo "Target: $SNIC_TMP/krakenuniq_db"
echo "Time: $(date)" 

# Ensure target directory does not already exist
rm -rf $SNIC_TMP/krakenuniq_db

# -L ensures symlinks are dereferenced (actual data is copied)
cp -rL "$db" "$SNIC_TMP/krakenuniq_db"

echo "Database copy complete."
echo "Time: $(date)"
echo "Database size on local SSD:"
du -sh $SNIC_TMP/krakenuniq_db

# Set database path
db_local=$SNIC_TMP/krakenuniq_db

for sample in $(cat ${samples}); do

    echo "Performing KrakenUniq classification for sample: ${sample}"
    echo "Node: $(hostname)"
    echo "Time: $(date)"

    krakenuniq --db "$db_local" \
    --fastq-input ${base}/data/01_host_removal/${sample}_unaligned_to_hg38.fastq.gz \
    --threads 16 --classified-out ${base}/data/02_krakenuniq/${sample}.classified_sequences.krakenuniq \
    --unclassified-out ${base}/data/02_krakenuniq/${sample}.unclassified_sequences.krakenuniq \
    --output ${base}/data/02_krakenuniq/${sample}.sequences.krakenuniq \
    --report-file ${base}/data/02_krakenuniq/${sample}.krakenuniq.output

    echo "Done with KrakenUniq classification for sample: ${sample}"
    echo "Time: $(date)"

done

echo "Done with KrakenUniq classification for all samples"